### ISSUE TITLE
Cannot compile and build.  Pre-built Jar file should be available.

### ISSUE THREAD

**Issue by PowerUser1234** [yuemingl/SymJava#4]
There should be an active link to a pre-built .jar file for SymJava available.

**Comment by yuemingl** [comment]
Thanks. I uploaded a jar in the release.

**Comment by yuemingl** [comment]
You can fine the jar file in this page https://github.com/yuemingl/SymJava/releases

**Comment by xinxilwl** [comment]
Hi, the repo contains the jar file only supported by Java7, could you offer a Java8 supported Version? 
Actually, when I use the jar, I get the Exception below:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/org/apache/bcel/internal/generic/InstructionConstants
	at symjava.symbolic.utils.BytecodeUtils.genClassBytecodeFunc(BytecodeUtils.java:274)
	at symjava.symbolic.Func.toBytecodeFunc(Func.java:75)
	at symjava.symbolic.Func.toBytecodeFunc(Func.java:60)
```
My Java code is below:
```
public static void main(String[] args) {

        System.out.println(x & y);
        System.out.println(x | y);
        System.out.println(x ^ y);
        System.out.println(~x);

        System.out.println(Gt.apply(x, y) | Gt.apply(x, z));
        System.out.println(Ge.apply(x, y) | Ge.apply(x, z));
        System.out.println(Le.apply(x, y) | Le.apply(x, z));
        System.out.println(Lt.apply(x, y) | Lt.apply(x, z));
        System.out.println(Neq.apply(x, y) | Neq.apply(x, z));

	Func f1 = new Func("fun1", Gt.apply(x, y) ^ Gt.apply(x, z));

        BytecodeFunc ff1 = f1.toBytecodeFunc(); // The line raises an exception mentioned above.
        System.out.println(ff1.apply(5,3));
    }
```
While I find out the Exception from BytecodeUtils.class file, I get a notice, decompiled .class file bytecode version:51.0(java 7), my Java compiler is Java8. So the jar maybe compiled by Java7. And it doesn't work in my project.
